### ISSUE TITLE
Roadmap for service design in 'Review' project

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#59]
Where does service design come in with the review project? Let's map it out! (note: this ticket is closely related to #60)

Acceptance Criteria: 
- [x] Map out key DST priorities
- [x] Map out key branch priorities
- [x] Identify needed service design activities
- [x] Arrange activities in timeline/roadmap on whiteboard
- [x] Upload photos to Miro
- [x] Digitize roadmap
- [x] Pass to scrum team for feedback
