### ISSUE TITLE
Flesh out team's roadmap to 2026

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#60]
Lots of things to do! Let's build out our team's roadmap to capture key priorities leading up to 2026.

Acceptance Criteria:
- [x] Review existing roadmap
- [x] Review priorities from now to 2026
- [x] Build out draft roadmap
- [x] Pass to scrum team for feedback
- [x] Iterate on feedback

**Comment by jaimiebutton** [comment]
Hey @LindsayMacfarlane, I added this ticket as a result of our conversation last Friday. Is there anything you'd like to make sure we capture here?

**Comment by LindsayMacfarlane** [comment]
@jaimiebutton - overall captures everything. Let's book some time early sprint to flesh things out at a high level from April 1 2023 to January 2026.
