### ISSUE TITLE
Roll up DST's 2026 roadmap into surge team's

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#61]
Following ticket #60 when we have a roadmap ready to go for DST, let's roll ours up into the surge team's big-picture roadmap.

Acceptance criteria:
- [ ] Simplify roadmap as needed
- [ ] Transfer contents over to surge team's roadmap
- [ ] Pass to surge team for feedback
- [ ] Iterate on feedback, if needed
