### ISSUE TITLE
Plan for Discovery on Metabase (DST)

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-review#67]
#### Task:
Conduct 'discovery light' on current metabase use and accessibility to better understand user needs. Results will help inform decisions on whether Metabase is still the appropriate tool to support the branch or if an alternative needs to be aquired.

#### Checklist:
- [x] Identify goals of metabase discovery
- [x] Identify discovery participants
- [x] Create research questions 
- [x] Create survey skeleton in Miro
- [x] Pass to project team for feedback
- [x] Get feedback from project team

**Comment by LindsayMacfarlane** [comment]
Excited for this @jaimiebutton !
