### ISSUE TITLE
Plan for Discovery Light (DST)

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#71]
#### Task:
Plan for initial light discovery with program areas to better understand potential digital service needs of the branch in the next 1-3 years.

#### Checklist:
- [x] identify goals of Discovery Lite
- [x] Write questions
- [x] Create Miro board link for Discovery Lite
- [x] Create skeleton miro structure
- [x] Build out miro facilitation space
- [x] Pass to project team for feedback
- [x] Iterate on feedback if needed

#### Notes:

**Comment by LindsayMacfarlane** [comment]
Excited for this @jaimiebutton!
